/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jesus Osco (https://sketchfab.com/gsus.vfx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mjolnir-thor-love-and-thunder-9689a953a9724987bb962bc00104c5fd
Title: Mjolnir - Thor love and thunder
*/

import { useGLTF } from '@react-three/drei'
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';

export default function Hammer({ src = '/models/hammer.glb', ...props }) {
  const { nodes, materials } = useGLTF(src)
  const hammerEl = useRef();

  useFrame((state, delta) => {
    if(hammerEl.current)
      hammerEl.current.rotation.y += 0.01;
      hammerEl.current.rotation.x += 0.01;
  });
  return (
    <group {...props} ref={hammerEl} dispose={null}>
      <group rotation={[-Math.PI, -0.053, -Math.PI]} userData={{ name: 'Mjolnir_5' }}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Grip}
          position={[0, 0.3, 0]}
          userData={{ name: 'Object_5' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.GripBottom}
          position={[0, 0.3, 0]}
          userData={{ name: 'Object_7' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Hammer}
          position={[0, 0.3, 0]}
          userData={{ name: 'Object_9' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.Strap}
          position={[0, 0.302, 0]}
          userData={{ name: 'Object_11' }}
        />
      </group>
    </group>
  )
}
